---
version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging into Docker Hub...
      - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME"
        --password-stdin
      - IMAGE_TAG="latest"
  build:
    commands:
      - echo Pulling the latest Docker image from Docker Hub...
      - docker pull satya368/go-mechanic-tracker:latest
      - docker tag satya368/go-mechanic-tracker:latest satya368/go-mechanic-tracker:$IMAGE_TAG
  post_build:
    commands:
      - echo Writing Dockerrun.aws.json file...
      - |
        cat <<EOF > Dockerrun.aws.json
        {
          "AWSEBDockerrunVersion": "1",
          "Image": {
            "Name": "satya368/go-mechanic-tracker:$IMAGE_TAG",
            "Update": "true"
          },
          "Ports": [
            {
              "ContainerPort": 80
            }
          ]
        }
        EOF
      - echo Build completed on `date`
artifacts:
  files:
    - Dockerrun.aws.json
