---
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into Docker Hub..."
      - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
      - export IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - echo "Using image tag: $IMAGE_TAG"
      - echo "IMAGE_TAG=$IMAGE_TAG" > env_vars  # Save to env_vars file

  build:
    commands:
      - source env_vars  # Load IMAGE_TAG
      - echo "Building the Docker image..."
      - docker build -t satya368/go-mechanic-tracker:$IMAGE_TAG .
      - echo "Pushing the image to Docker Hub..."
      - docker push satya368/go-mechanic-tracker:$IMAGE_TAG

  post_build:
    commands:
      - source env_vars  # Load IMAGE_TAG again
      - echo "Writing Dockerrun.aws.json file..."
      - |
        echo '{
          "AWSEBDockerrunVersion": "1",
          "Image": {
            "Name": "satya368/go-mechanic-tracker:'"$IMAGE_TAG"'",
            "Update": "true"
          },
          "Ports": [
            {
              "ContainerPort": 80
            }
          ]
        }' > Dockerrun.aws.json
      - echo "Build completed on $(date)"

artifacts:
  files:
    - Dockerrun.aws.json
